version: '3.0'

services:
  grafana:
    container_name: 'opennms-helm-app'
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-9.4.7}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/opennms-helm-app
      - ./provisioning:/etc/grafana/provisioning
