# This is an example with only required properties:
version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"
    default_reviewers:
      - "rangerrick"
      - "j-white"
    default_labels:
      - "dependabot"
    commit_message:
      prefix: "build"
      include_scope: true
